import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import Sidebar from "@/components/Sidebar";

const geistSans = localFont({
    src: "../fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "../fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Falcon Insights",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="antialiased">
                <div className="flex h-screen overflow-hidden">
                    {/* Sidebar - Fixed and Full Height */}
                    <Sidebar />
                    {/* Main Content - Positioned Next to Sidebar and Scrollable */}
                    <div className="flex-1 md:ml-72 m-0 overflow-y-auto">
                        {children}
                    </div>
                </div>
            </body>
        </html>
    );
}
